FROM ubuntu:18.04
RUN  apt-get update
RUN  apt-get -y install curl
RUN  apt-get -y install procps
RUN  apt-get -y install net-tools
RUN  apt-get -y install apache2
RUN  apt-get -y install perl
RUN  apt-get -y install python3
