FROM amazonlinux:2
RUN yum install -y python3 python3-pip
RUN pip3 install distro
RUN yum install -y perl
RUN yum install -y php
RUN yum install -y which
RUN yum install -y curl
RUN yum install -y net-tools
RUN yum install -y hostname
RUN yum install -y procps
RUN yum install -y httpd
RUN yum install -y httpd-tools
